# Generated by Django 6.0 on 2026-08-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brideName', models.CharField(max_length=1000)),
                ('brideDOB', models.DateField()),
                ('brideEmail', models.EmailField(max_length=254, unique=True)),
                ('brideFatherName', models.CharField(max_length=1000)),
                ('brideMotherName', models.CharField(max_length=1000)),
                ('brideAddress', models.CharField(max_length=1000)),
                ('brideNidNo', models.CharField(max_length=1000)),
                ('brideImage', models.ImageField(upload_to='documents/')),
                ('brideNidImage', models.ImageField(upload_to='documents/')),
                ('is_valid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groomName', models.CharField(max_length=1000)),
                ('groomDOB', models.DateField()),
                ('groomEmail', models.EmailField(max_length=254, unique=True)),
                ('groomFatherName', models.CharField(max_length=1000)),
                ('groomMotherName', models.CharField(max_length=1000)),
                ('groomAddress', models.CharField(max_length=1000)),
                ('groomNidNo', models.CharField(max_length=1000)),
                ('groomImage', models.ImageField(upload_to='documents/')),
                ('groomNidImage', models.ImageField(upload_to='documents/')),
                ('is_document_valid', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarrigaeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('approve', 'Approve')], default='Pending', max_length=1000)),
                ('marriageDate', models.DateField()),
                ('registrationDate', models.DateField()),
                ('place_of_marriage', models.CharField(max_length=1000)),
                ('bride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bride')),
                ('groom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groom')),
            ],
        ),
        migrations.CreateModel(
            name='MarriageRecorde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateNo', models.CharField(max_length=100)),
                ('issuedDate', models.DateField(auto_now_add=True)),
                ('marriageRequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.marrigaerequest')),
            ],
        ),
    ]
