# Generated by Django 6.1 on 2026-08-12 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrideTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brideName", models.CharField(max_length=1000)),
                ("brideDOB", models.DateField()),
                ("brideEmail", models.EmailField(max_length=254, unique=True)),
                ("brideFatherName", models.CharField(max_length=1000)),
                ("brideMotherName", models.CharField(max_length=1000)),
                ("brideAddress", models.CharField(max_length=1000)),
                ("brideNidNo", models.CharField(max_length=1000)),
                ("brideImage", models.ImageField(upload_to="documents/")),
                ("brideNidImage", models.ImageField(upload_to="documents/")),
                ("is_valid", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="groom",
            name="newBride",
        ),
        migrations.CreateModel(
            name="GroomTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("groomName", models.CharField(max_length=1000)),
                ("groomDOB", models.DateField()),
                ("groomEmail", models.EmailField(max_length=254, unique=True)),
                ("groomFatherName", models.CharField(max_length=1000)),
                ("groomMotherName", models.CharField(max_length=1000)),
                ("groomAddress", models.CharField(max_length=1000)),
                ("groomNidNo", models.CharField(max_length=1000)),
                ("groomImage", models.ImageField(upload_to="documents/")),
                ("groomNidImage", models.ImageField(upload_to="documents/")),
                ("is_document_valid", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.bridetable"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Birde",
        ),
        migrations.DeleteModel(
            name="Groom",
        ),
    ]
