# Generated by Django 6.0 on 2026-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bridetable_remove_groom_newbride_groomtable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomtable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reject', 'Reject'), ('approve', 'Approve')], default='pending', max_length=1000),
        ),
    ]
